feature/86ep3ht47/Bowtie-Drag-n-Drop
Modern-Resolve-Developers/nclexpower_turbo pull request #27
Opened 2024-04-20 16:50 UTC by acostales08

2024-04-20 18:04 UTC, JezChristian approved these changes
Galing!!!!

2024-04-20 18:39 UTC, JMSevilla requested changes

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/db.json
> +                                "selectFieldKey": [
This should not be `selectFieldKey` change the property name according to the questionnaire.

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtieComponent/DraggableCard.tsx
> +    icon?: boolean | undefined
Why we are passing icon as props? icon should not be an optional it is always included in your component.

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtieComponent/Droppable.tsx
> +export const DroppableContainer: React.FC<Props> = ({accept, text, bg, onDrop, droppedValue, handleRemove }) => {
avoid prop drilling, you can use ...others or ...rest

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtieComponent/DraggableCard.tsx
> +export const DraggableCard: React.FC<Props> = ({ onClick, answer, bg, icon, type}) => {
avoid prop drilling, you can use ...others or ...rest

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtieComponent/Droppable.tsx
> +                <p className='opacity-35'>{text}</p>
Is this kind of catch ? is your `droppedValue` can possibly be empty? if not you can use `droppedValue.length > 0 &&`

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtieComponent/ItemTypes.tsx
> +    Third: "Parameters To Monitor"
Inconsistent casing.

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtieComponent/ItemTypes.tsx
> +  export default itemTypes;
using export default is for classes only. you can use `export const itemTypes` 
[suggestion] create a folder in core folder named `constants`

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtieQuestionaire.tsx
> +  "first": [],
your containerState should have a proper naming convension. (e.g., ActionToTake1, ActionToTake2) with this naming convention we can easily identify your containerState

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtieQuestionaire.tsx
> +  const [dropContainer] = useState([
Data is too messy you can transfer those in constants.

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDBowtieQuestionaire.tsx
> +                              {/* <h3 className="text-center p-2">{key}</h3> */}
remove

2024-04-20 18:39 UTC, JMSevilla commented on apps/simulator/src/core/types/ssrData.ts
> +  ChoicesList: any
Can we identify the types for this instead of any ?

2024-04-21 08:38 UTC, JMSevilla requested changes
Please address all the comments

2024-04-21 17:06 UTC, DropitupQwerty approved these changes

2024-04-22 10:16 UTC, JMSevilla approved these changes

2024-04-22 10:49 UTC, merged