@feature/86ep326h3/dnd-validation ft code enhancement
Modern-Resolve-Developers/nclexpower_turbo pull request #32
Opened 2024-04-28 13:26 UTC by DropitupQwerty

- Deletion of unused files
- Creation of Reusable Component
- Adding types

2024-04-28 14:48 UTC, JMSevilla requested changes
Clarification and request changes.

2024-04-28 14:48 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/DNDComponent/WordDropContainer.tsx
> +export const WordDropContainer: React.FC<Props> = ({ placeholder, name, onDelete, onDropped, setWord }) => {
prevent prop drilling, use ...rest

2024-04-28 14:48 UTC, JMSevilla commented on apps/simulator/src/core/types/ssrData.ts
> +  DND1WordChoice1: Array<any>;
Why we are using `Array<any>` ?

2024-04-28 14:48 UTC, JMSevilla commented on packages/utils/types/preloaded-types/preloaded-types-responses/index.ts
> +  rows: string | Array<any>;
If rows can store different values of data then you can just use string | any or any.

2024-04-28 15:46 UTC, DropitupQwerty commented on packages/utils/types/preloaded-types/preloaded-types-responses/index.ts
> +  rows: string | Array<any>;
My Bad po Sir in this area. Di po talaga dapat sya included sa push ko

2024-04-29 07:18 UTC, JMSevilla approved these changes

2024-04-29 08:34 UTC, JezChristian approved these changes

2024-04-29 10:20 UTC, acostales08 approved these changes

2024-04-29 15:01 UTC, acostales08 approved these changes

2024-04-29 15:02 UTC, merged