Feature/56810847/regular-question-sata ft Answer UI as Table and List
Modern-Resolve-Developers/nclexpower_turbo pull request #7
Opened 2024-03-29 19:04 UTC by JezChristian

2024-03-30 01:50 UTC, JMSevilla requested changes
Major revision please addressed all the comments

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyContainer.tsx
> +
Don't always put empty interface/type to your code when pushing let's retain the cleanliness of our code. Or maybe you can add some properties with types that corresponds with the question

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyContainer.tsx
> +export const CaseStudyContainer: React.FC<Props> = ({ question }) => {
You already have export const don't need the export default below

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyContainer.tsx
> +export default CaseStudyContainer
Remove this code

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQNoGroup/MCQQuestion.tsx
Based on my observations with your interface/types declaration is this align with our DB.JSON? upon checking we don't have displayType, id, contentTitle in DB.json.

And can you please isolate this types to our types file inside core folder.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQNoGroup/MCQQuestion.tsx
> +                    <p> {question.question}</p>
Why you are using `question.question` if the question is an array ? is this code not giving you any error ? same with the others below

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQNoGroup/MCQQuestion.tsx
> +                    <div key={question?.qId} className='flex gap-1'>
Why you are using qId as key? always use index in key={}

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQNoGroup/MCQQuestion.tsx
> +                        {question.tabs && question.tabs.map((tab: any, tabIndex) => (
don't use `question.tabs` instead use `question.tabs?.length > 0`

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQNoGroup/MCQQuestion.tsx
>                              <div key={tab.tabId} className={`px-5 py-1 rounded-t-md text-sm font-semibold flex items-center cursor-pointer hover:bg-slate-100 ${activeTab === tabIndex ? ' underline bg
Don't use tab.tabId use index

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQNoGroup/MCQQuestion.tsx
> +                        <div key={question?.qId} className='flex flex-col gap-y-4'>
don't use `qId` as key use index

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQNoGroup/MCQQuestion.tsx
> +                            {question.tabs && question.tabs.map((tab, tabIndex) => (
instead of `question.tabs` use `question.tabs?.length > 0`

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQNoGroup/MCQQuestion.tsx
> +                    <li>{answer && answer.map((ans) => (
Don't use this kind of conditional code `answer` use `answer?.length > 0`

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQAnswerTable.tsx
>  import React from 'react'
Why you are creating `MCQAnswerTable.tsx` for each folder? can you just create a reusable component under `packages` folder ? kindly follow the best practices.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
> +    tabsId: string
tabsId is not a string it is a number please follow the DB.json

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
> +interface TabsData {
Can you just put this type to our types file and just import it?

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
>  interface QuestionData {
From this interface the QuestionData is not lack of properties but on your previous QuestionData it has complete properties. kindly just create a type in types file and just reuse it so we can prevent this confusion

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
>  interface AnswerData {
Transfer this file in a single file on our types file. and just import it

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
> +    question: QuestionData
From this code the QuestionData is not an object? but on your previous code it is an array kindly please follow the consistent pattern and especially our DB.json

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
> +    answer: AnswerData[]
Why we are still passing answer array here? did we already talked about this ?

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
> +export const MCQGroupQuestion: React.FC<Props> = ({ question, answer }: Props) => {
from `export const MCQGroupQuestion: React.FC<Props> = ({ question, answer }: Props)`

to 
`export const MCQGroupQuestion: React.FC<Props> = ({ question, answer })`

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
> +                    <p> {question.question}</p>
question is not an object this is not the proper way of using it.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
> +                        {question.tabs && question.tabs.map((tab: any, tabIndex) => (
use question.tabs?.length > 0

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
>                              <div key={tab.tabId} className={`px-5 py-1 rounded-t-md text-sm font-semibold flex items-center cursor-pointer hover:bg-slate-100 ${activeTab === tabIndex ? ' underline bg
don't use `tab.tabId` in keys use index from map

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
> +                        <div key={question?.qId} className='flex flex-col gap-y-4'>
from this code it is identified that the `qId` can be possibly null or undefined add some iterations condition here for us to have a catch

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/MCQWithGroup/MCQGroupQuestion.tsx
> +                            {question.tabs && question.tabs.map((tab, tabIndex) => (
use `question.tabs?.length > 0`

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/SATA/SATAQuestion.tsx
> +    question: QuestionData[]
from this code the question comes back to array.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/SATA/SATAQuestion.tsx
>  interface QuestionData {
the properties and types is mismatch from the DB.json

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/SATA/SATAQuestion.tsx
> +    console.log("question : ", question)
Remove console logs.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/SATA/SATAQuestion.tsx
> +                    <p> {question.question}</p>
You can't access question in this way since it is an array? how your IDE letting you do this kind of code.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/SATA/SATATable.tsx
> +import React, { ReactNode } from 'react'
Kindly please create a reusable component for all the tables you need and don't recreate them for each folder. please follow the best practices of react.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/SATA/SATATable.tsx
> +    "title": string;
don't use "title" instead use title: string

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/SATA/SATATable.tsx
> +    value: string[]
Since this is a SATA , why our value is string[] ? is our checkbox giving us an output of string or boolean?

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/RegularQuestion/SATA/SATAQuestion.tsx
> +interface QuestionData {
Don't recreate this interface it is already in the types file why you didn't just import this ? please follow the best practices of programming.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/RegularQuestion/SATA/SATAQuestion.tsx
> +    question: QuestionData
question is not an object it is an array.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/RegularQuestion/SATA/SATAQuestion.tsx
> +        <div className='w-full h-full flex'>
Same comments below kindly use the top comments for reference.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/RegularQuestion/SATA/SATAQuestion.tsx
> +                {answer && answer.map((answerItem) => (
Also as part of the best practices all your maps can you add a type for each items ? 

example : answer.map((answerItem: AnswerItemTypes) => )

The IDE should give you an error since it will detect that the answerItem is an any type

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/RegularQuestion/SATA/SATAQuestion.tsx
> +                                            <span><Checkbox sx={{ height: "20px" }} /></span>
The checkbox is not returning a value ?

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/RegularQuestion/SATA/SATATable.tsx
> +import { Checkbox, Grid, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from '@mui/material'
Can you create a reusable component for this component.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/RegularQuestion/SATA/SATATable.tsx
> +                            <div key={answerItem.answerId} className='w-full'>
answerItem.answerId will give you an any type since it is not defined on your answerItem

to resolve this you can create a type from our types file and define all the types you are using for your mapping.

2024-03-30 01:50 UTC, JMSevilla commented on apps/simulator/src/components/blocks/RegularQuestion/SATA/SATATable.tsx
> +                                                    {answerItem.rows.map((row: any) => (
Don't use row: any , create a type on our types file define the type for each property in the row object.

2024-03-30 01:51 UTC, JMSevilla requested changes
Addressed all the request changes

2024-04-02 07:16 UTC, JMSevilla requested changes

2024-04-02 07:16 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/MCQTable/MCQAnswerGroupTable.tsx
>      return (
What I said last time, can you please make this component reusable as one ? As you can see your `MCQAnswerGroupTable` and `MCQAnswerNoGroupTable` is almost the same. You can refactor your table and make it just 1 file only. delete the other one and use conditional rendering instead.

2024-04-02 07:16 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/MCQTable/MCQAnswerNoGroupTable.tsx
>      return (
What I said last time, can you please make this component reusable as one ? As you can see your `MCQAnswerGroupTable` and `MCQAnswerNoGroupTable` is almost the same. You can refactor your table and make it just 1 file only. delete the other one and use conditional rendering instead.

2024-04-02 07:56 UTC, JMSevilla requested changes

2024-04-02 07:56 UTC, JMSevilla commented on apps/simulator/src/components/blocks/CaseStudy/CaseStudyQuestions/MCQTable/MCQAnswerGroupTable.tsx
> +                                                        {answerItem?.QType === "Group" ?
Change the condition if true it should render the `renderCheckboxes` or else render the `renderRadioButtons`

2024-04-02 07:56 UTC, JMSevilla commented on apps/simulator/src/core/types/ssrData.ts
> +  QType?: string
Do we really need the QType if we already have answerType and the answer array is also inside the questionaire ?

2024-04-02 11:01 UTC, JMSevilla approved these changes

2024-04-02 11:04 UTC, acostales08 approved these changes

2024-04-03 10:41 UTC, merged